# // Generated by Vorto from org.eclipse.vorto.Connectivity

class Connectivity(object):
    def __init__(self):
        self.rssi = 0.0
        self.snr = 0.0
        self.lastSeen = 0.0
        self.status = 0.0

    ### Status property rssi
    @property
    def rssi(self):
        return self.__rssi[0]
    
    @rssi.setter
    def rssi(self, value):
        self.__rssi = (value, True)
    
    ### Status property snr
    @property
    def snr(self):
        return self.__snr[0]
    
    @snr.setter
    def snr(self, value):
        self.__snr = (value, True)
    
    ### Status property lastSeen
    @property
    def lastSeen(self):
        return self.__lastSeen[0]
    
    @lastSeen.setter
    def lastSeen(self, value):
        self.__lastSeen = (value, True)
    
    ### Status property status
    @property
    def status(self):
        return self.__status[0]
    
    @status.setter
    def status(self, value):
        self.__status = (value, True)
    
    def serializeStatus(self, serializer):
        serializer.first_prop = True
        if self.__rssi[1]:
               serializer.serialize_property("rssi", self.__rssi[0])
               self.__rssi = (self.__rssi[0], False)
        if self.__snr[1]:
               serializer.serialize_property("snr", self.__snr[0])
               self.__snr = (self.__snr[0], False)
        if self.__lastSeen[1]:
               serializer.serialize_property("lastSeen", self.__lastSeen[0])
               self.__lastSeen = (self.__lastSeen[0], False)
        if self.__status[1]:
               serializer.serialize_property("status", self.__status[0])
               self.__status = (self.__status[0], False)
    def serializeConfiguration(self, serializer):
        pass
