/**
 * Copyright (c) 2015 Bosch Software Innovations GmbH and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v1.0 which accompany this distribution.
 * 
 * The Eclipse Public License is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * The Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 * 
 * Contributors:
 * Bosch Software Innovations GmbH - Please refer to git log
 */
package org.eclipse.vorto.codegen.coap.common.templates;

import com.google.common.base.Objects;
import org.eclipse.vorto.codegen.api.ITemplate;
import org.eclipse.vorto.codegen.api.InvocationContext;
import org.eclipse.vorto.codegen.coap.CoAPUtils;
import org.eclipse.vorto.core.api.model.functionblock.Operation;
import org.eclipse.vorto.core.api.model.functionblock.ReturnType;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.StringExtensions;

@SuppressWarnings("all")
public class JavaFBOperationReturnPrimitiveTypeWrapperTemplate implements ITemplate<Operation> {
  private String className;
  
  private String classPackage;
  
  public JavaFBOperationReturnPrimitiveTypeWrapperTemplate(final String className, final String classPackage) {
    this.className = className;
    this.classPackage = classPackage;
  }
  
  @Override
  public String getContent(final Operation op, final InvocationContext invocationContext) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/*");
    _builder.newLine();
    _builder.append("*****************************************************************************************");
    _builder.newLine();
    _builder.append("* The present code has been generated by the Eclipse Vorto CoAP Code Generator.");
    _builder.newLine();
    _builder.append("*");
    _builder.newLine();
    _builder.append("* The basis for the generation was the Information Model which is uniquely identified by:");
    _builder.newLine();
    _builder.append("* Name:\t\t\t");
    _builder.append(this.className, "");
    _builder.newLineIfNotEmpty();
    _builder.append("* Namespace:\t");
    _builder.append(this.classPackage, "");
    _builder.newLineIfNotEmpty();
    _builder.append("* Version:\t\t");
    _builder.newLine();
    _builder.append("*****************************************************************************************");
    _builder.newLine();
    _builder.append("*/");
    _builder.newLine();
    _builder.newLine();
    _builder.append("package ");
    _builder.append(this.classPackage, "");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class ");
    String _firstUpper = StringExtensions.toFirstUpper(this.className);
    _builder.append(_firstUpper, "");
    _builder.append(" {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private ");
    String _returnTypeAsString = CoAPUtils.getReturnTypeAsString(op);
    _builder.append(_returnTypeAsString, "\t");
    _builder.append(" value;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    {
      ReturnType _returnType = op.getReturnType();
      boolean _notEquals = (!Objects.equal(_returnType, null));
      if (_notEquals) {
        _builder.append("\t");
        _builder.append("public ");
        String _returnTypeAsString_1 = CoAPUtils.getReturnTypeAsString(op);
        _builder.append(_returnTypeAsString_1, "\t");
        _builder.append(" getValue() {");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("return value;");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("public void setValue(");
        String _returnTypeAsString_2 = CoAPUtils.getReturnTypeAsString(op);
        _builder.append(_returnTypeAsString_2, "\t");
        _builder.append(" value) {");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("this.value = value; ");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("\t");
        _builder.newLine();
      }
    }
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }
}
