# org.eclipse.vorto.tutorials.RaspberryPiTutorial generated by Vorto Python MQTT Generator

import model.functionblock.Location as location
import model.functionblock.Battery as battery
import model.functionblock.Temperature as cpuTemperature

class RaspberryPiTutorial(object):
    def __init__(self):
        self.location = location.Location()
        self.battery = battery.Battery()
        self.cpuTemperature = cpuTemperature.Temperature()
