package org.eclipse.vorto.codegen.kura.templates;

import java.util.Map;
import org.eclipse.vorto.codegen.api.IFileTemplate;
import org.eclipse.vorto.codegen.api.InvocationContext;
import org.eclipse.vorto.codegen.kura.templates.Utils;
import org.eclipse.vorto.core.api.model.informationmodel.InformationModel;
import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class PomTemplate implements IFileTemplate<InformationModel> {
  @Override
  public String getFileName(final InformationModel context) {
    return "pom.xml";
  }
  
  @Override
  public String getPath(final InformationModel context) {
    StringConcatenation _builder = new StringConcatenation();
    String _basePath = Utils.getBasePath(context);
    _builder.append(_basePath, "");
    return _builder.toString();
  }
  
  @Override
  public String getContent(final InformationModel element, final InvocationContext context) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
    _builder.newLine();
    _builder.append("<project xmlns=\"http://maven.apache.org/POM/4.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<modelVersion>4.0.0</modelVersion>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<groupId>org.eclipse.vorto.kura</groupId>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<artifactId>");
    String _name = element.getName();
    String _lowerCase = _name.toLowerCase();
    _builder.append(_lowerCase, "\t");
    _builder.append("</artifactId>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<version>1.0.0-SNAPSHOT</version>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<packaging>jar</packaging>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<name>Kura Bundle for ");
    String _name_1 = element.getName();
    _builder.append(_name_1, "\t");
    _builder.append("</name>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<description>Kura Bundle for ");
    String _name_2 = element.getName();
    _builder.append(_name_2, "\t");
    _builder.append("</description>");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<properties>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<java.version>1.8</java.version>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</properties>");
    _builder.newLine();
    {
      Map<String, String> _configurationProperties = context.getConfigurationProperties();
      String _orDefault = _configurationProperties.getOrDefault("boschcloud", "false");
      boolean _equalsIgnoreCase = _orDefault.equalsIgnoreCase("true");
      if (_equalsIgnoreCase) {
        _builder.append("\t");
        _builder.append("<repositories>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("<repository>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<id>bosch-releases</id>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<name>bosch-releases</name>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<url>https://maven.bosch-si.com/content/repositories/bosch-releases/</url>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("</repository>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("</repositories>");
        _builder.newLine();
        _builder.newLine();
        _builder.append("\t");
        _builder.append("<dependencies>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("<dependency>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<groupId>com.bosch.cr</groupId>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<artifactId>cr-integration-api</artifactId>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<version>3.3.0</version>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("</dependency>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("<dependency>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<groupId>com.bosch.cr</groupId>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<artifactId>cr-integration-client</artifactId>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<version>2.4.1</version>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("</dependency>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("<dependency>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<groupId>com.bosch.cr</groupId>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<artifactId>cr-integration-client-osgi</artifactId>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<version>2.4.1</version>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("</dependency>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("<dependency>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<groupId>com.bosch.cr</groupId>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<artifactId>cr-json</artifactId>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<version>1.6.0</version>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("</dependency>");
        _builder.newLine();
      } else {
        _builder.append("\t");
        _builder.append("<repositories>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("<repository>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<id>Eclipse Paho Repo</id>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<url>https://repo.eclipse.org/content/repositories/paho-releases/</url>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("</repository>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("</repositories>");
        _builder.newLine();
        _builder.newLine();
        _builder.append("\t");
        _builder.append("<dependencies>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("<dependency>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<groupId>org.eclipse.paho</groupId>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<artifactId>org.eclipse.paho.client.mqttv3</artifactId>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("<version>1.0.2</version>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("</dependency>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("<dependency>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t    ");
        _builder.append("<groupId>com.google.code.gson</groupId>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t    ");
        _builder.append("<artifactId>gson</artifactId>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t    ");
        _builder.append("<version>2.8.1</version>");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("</dependency>");
        _builder.newLine();
      }
    }
    _builder.append("\t");
    _builder.append("</dependencies>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<build>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<plugins>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<plugin>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<groupId>org.apache.maven.plugins</groupId>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<artifactId>maven-dependency-plugin</artifactId>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<version>3.0.1</version>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<configuration>");
    _builder.newLine();
    _builder.append("        \t");
    _builder.append("<outputDirectory>${basedir}/lib</outputDirectory>");
    _builder.newLine();
    _builder.append("        \t");
    _builder.append("<overWriteReleases>false</overWriteReleases>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<overWriteSnapshots>false</overWriteSnapshots>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<overWriteIfNewer>true</overWriteIfNewer>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</configuration>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</plugin>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</plugins>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</build>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("</project>");
    _builder.newLine();
    return _builder.toString();
  }
}
