/**
 * Copyright (c) 2015-2016 Bosch Software Innovations GmbH and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v1.0 which accompany this distribution.
 * 
 * The Eclipse Public License is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * The Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 * 
 * Contributors:
 * Bosch Software Innovations GmbH - Please refer to git log
 */
package org.eclipse.vorto.codegen.kura.templates.osgiinf;

import java.util.Map;
import org.eclipse.emf.common.util.EList;
import org.eclipse.vorto.codegen.api.IFileTemplate;
import org.eclipse.vorto.codegen.api.InvocationContext;
import org.eclipse.vorto.codegen.kura.templates.Utils;
import org.eclipse.vorto.core.api.model.informationmodel.FunctionblockProperty;
import org.eclipse.vorto.core.api.model.informationmodel.InformationModel;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.StringExtensions;

@SuppressWarnings("all")
public class MetatypeTemplate implements IFileTemplate<InformationModel> {
  @Override
  public String getFileName(final InformationModel context) {
    StringConcatenation _builder = new StringConcatenation();
    String _javaPackage = Utils.getJavaPackage(context);
    _builder.append(_javaPackage, "");
    _builder.append(".");
    String _name = context.getName();
    _builder.append(_name, "");
    _builder.append("BluetoothFinder.xml");
    return _builder.toString();
  }
  
  @Override
  public String getPath(final InformationModel context) {
    StringConcatenation _builder = new StringConcatenation();
    String _basePath = Utils.getBasePath(context);
    _builder.append(_basePath, "");
    _builder.append("/OSGI-INF/metatype");
    return _builder.toString();
  }
  
  @Override
  public String getContent(final InformationModel element, final InvocationContext context) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
    _builder.newLine();
    _builder.append("<MetaData xmlns=\"http://www.osgi.org/xmlns/metatype/v1.2.0\" localization=\"en_us\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<OCD id=\"");
    String _javaPackage = Utils.getJavaPackage(element);
    _builder.append(_javaPackage, "    ");
    _builder.append(".");
    String _name = element.getName();
    _builder.append(_name, "    ");
    _builder.append("BluetoothFinder\"");
    _builder.newLineIfNotEmpty();
    _builder.append("         ");
    _builder.append("name=\"");
    String _displayname = element.getDisplayname();
    _builder.append(_displayname, "         ");
    _builder.append(" Bluetooth Finder\" ");
    _builder.newLineIfNotEmpty();
    _builder.append("         ");
    _builder.append("description=\"App that reads ");
    String _displayname_1 = element.getDisplayname();
    _builder.append(_displayname_1, "         ");
    _builder.append(" data via bluetooth and sends it to the IoT cloud backend.\">");
    _builder.newLineIfNotEmpty();
    _builder.append("         ");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<Icon resource=\"http://vorto.eclipse.org/rest/model/image/");
    String _namespace = element.getNamespace();
    _builder.append(_namespace, "        ");
    _builder.append("/");
    String _name_1 = element.getName();
    _builder.append(_name_1, "        ");
    _builder.append("/");
    String _version = element.getVersion();
    _builder.append(_version, "        ");
    _builder.append("\" size=\"32\"/>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.newLine();
    {
      Map<String, String> _configurationProperties = context.getConfigurationProperties();
      String _orDefault = _configurationProperties.getOrDefault("boschcloud", "false");
      boolean _equalsIgnoreCase = _orDefault.equalsIgnoreCase("true");
      if (_equalsIgnoreCase) {
        _builder.append("\t\t");
        _builder.append("<AD id=\"boschcloud_solutionid\"");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("name=\"boschcloud_solutionid\"");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("type=\"String\" ");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("cardinality=\"0\"");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("required=\"true\"");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("default=\"\"");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("description=\"Bosch IoT Suite Solution ID\" />");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("<AD id=\"boschcloud_endpoint\"");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("name=\"boschcloud_endpoint\"");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("type=\"String\"");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("cardinality=\"0\"");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("required=\"true\"");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("default=\"wss://events.apps.bosch-iot-cloud.com\"");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("description=\"Bosch IoT Suite Endpoint\" />");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.newLine();
      } else {
        {
          Map<String, String> _configurationProperties_1 = context.getConfigurationProperties();
          String _orDefault_1 = _configurationProperties_1.getOrDefault("boschhub", "false");
          boolean _equalsIgnoreCase_1 = _orDefault_1.equalsIgnoreCase("true");
          if (_equalsIgnoreCase_1) {
            _builder.append("\t\t");
            _builder.append("<AD id=\"mqttHostUrl\"  ");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.append("name=\"mqttHostUrl\"");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.append("type=\"String\"");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.append("cardinality=\"0\" ");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.append("required=\"true\"");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.append("default=\"ssl://mqtt.bosch-iot-hub.com:8883\" ");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.append("description=\"The Bosch IoT Suite Hub URL\"/>");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("<AD id=\"hubTenant\"  ");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.append("name=\"hubTenant\"");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.append("type=\"String\"");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.append("cardinality=\"0\" ");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.append("required=\"true\"");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.append("default=\"DEFAULT_TENANT\" ");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.append("description=\"The Bosch IoT Hub Tenant\"/>");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.newLine();
          } else {
            _builder.append("\t\t");
            _builder.append("<AD id=\"publishTopic\"  ");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.append("name=\"publishTopic\"");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.append("type=\"String\"");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.append("cardinality=\"0\" ");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.append("required=\"true\"");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.append("default=\"\" ");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.append("\t");
            _builder.append("description=\"The topic to publish data to the Cloud.\"/>");
            _builder.newLine();
            _builder.append("\t\t");
            _builder.newLine();
          }
        }
      }
    }
    _builder.append("\t\t");
    _builder.append("<AD id=\"scan_enable\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("name=\"scan_enable\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("type=\"Boolean\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("cardinality=\"0\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("required=\"true\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("default=\"false\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("description=\"Enable scan for ");
    String _displayname_2 = element.getDisplayname();
    _builder.append(_displayname_2, "\t\t\t");
    _builder.append(" devices.\" />");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<AD id=\"scan_interval\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("name=\"scan_interval\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("type=\"Integer\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("cardinality=\"0\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("required=\"true\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("default=\"60\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("description=\"Interval of scan for devices in seconds.\" />");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<AD id=\"scan_time\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("name=\"scan_time\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("type=\"Integer\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("cardinality=\"0\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("required=\"true\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("default=\"10\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("description=\"Duration of scan for devices in seconds.\" />");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<AD id=\"update_interval\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("name=\"update_interval\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("type=\"Integer\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("cardinality=\"0\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("required=\"true\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("default=\"10\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("description=\"Interval of device update to Cloud in seconds\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<AD id=\"device_filter\"  ");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("name=\"device_filter\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("type=\"String\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("cardinality=\"0\" ");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("required=\"true\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("default=\"FC:D6:BD\" ");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("description=\"Filter for ");
    String _displayname_3 = element.getDisplayname();
    _builder.append(_displayname_3, "\t\t\t");
    _builder.append(" bluetooth devices\"/>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<AD id=\"iname\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("name=\"iname\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("type=\"String\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("cardinality=\"0\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("required=\"true\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("default=\"hci0\"");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("description=\"Name of bluetooth adapter.\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    {
      EList<FunctionblockProperty> _properties = element.getProperties();
      for(final FunctionblockProperty fbProperty : _properties) {
        _builder.append("\t\t");
        _builder.append("<AD id=\"enable");
        String _name_2 = fbProperty.getName();
        String _firstUpper = StringExtensions.toFirstUpper(_name_2);
        _builder.append(_firstUpper, "\t\t");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("name=\"enable");
        String _name_3 = fbProperty.getName();
        String _firstUpper_1 = StringExtensions.toFirstUpper(_name_3);
        _builder.append(_firstUpper_1, "\t\t\t");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("type=\"Boolean\"");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("cardinality=\"0\"");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("required=\"true\"");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("default=\"false\"");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("description=\"Enable ");
        String _name_4 = fbProperty.getName();
        _builder.append(_name_4, "\t\t\t");
        _builder.append(".\"/>");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.newLine();
      }
    }
    _builder.append("    ");
    _builder.append("</OCD>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<Designate pid=\"");
    String _javaPackage_1 = Utils.getJavaPackage(element);
    _builder.append(_javaPackage_1, "    ");
    _builder.append(".");
    String _name_5 = element.getName();
    _builder.append(_name_5, "    ");
    _builder.append("BluetoothFinder\">");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("<Object ocdref=\"");
    String _javaPackage_2 = Utils.getJavaPackage(element);
    _builder.append(_javaPackage_2, "        ");
    _builder.append(".");
    String _name_6 = element.getName();
    _builder.append(_name_6, "        ");
    _builder.append("BluetoothFinder\"/>");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("</Designate>");
    _builder.newLine();
    _builder.append("</MetaData>");
    _builder.newLine();
    _builder.newLine();
    return _builder.toString();
  }
}
