#!/bin/bash
export IMAGE_TAG=$TRAVIS_TAG;
echo "TRAVIS_TAG is $TRAVIS_TAG"
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
if [[ -n "$IMAGE_TAG" ]]; then
echo "IMAGE_TAG is $IMAGE_TAG"
docker push eclipsevorto/vorto-normalizer:latest
docker push eclipsevorto/vorto-normalizer:$IMAGE_TAG
else
docker push eclipsevorto/vorto-normalizer:nightly
fi
