/**
 * Copyright (c) 2017 Oliver Meili
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  and Eclipse Distribution License v1.0 which accompany this distribution.
 * 
 *  The Eclipse Public License is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 *  The Eclipse Distribution License is available at
 *  http://www.eclipse.org/org/documents/edl-v10.php.
 * 
 *  Contributors:
 *  Oliver Meili <omi@ieee.org>
 */
package org.eclipse.vorto.codegen.ble.alpwise.templates;

import org.eclipse.vorto.codegen.api.InvocationContext;
import org.eclipse.vorto.codegen.ble.templates.BleGattTemplate;
import org.eclipse.vorto.core.api.model.informationmodel.InformationModel;
import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class AlpwiseAppHeaderTemplate extends BleGattTemplate<InformationModel> {
  @Override
  public String getFileName(final InformationModel model) {
    return "BleApp.h";
  }
  
  @Override
  public String getPath(final InformationModel model) {
    return BleGattTemplate.rootPath;
  }
  
  @Override
  public String getContent(final InformationModel model, final InvocationContext context) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/* BLE Application Template generated by Vorto */");
    _builder.newLine();
    _builder.newLine();
    _builder.append("void BleApp_Init(void);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("void BleApp_ServicesInit(void);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("void BleApp_SensorsInit(void);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("void BleApp_Deinit(void);");
    _builder.newLine();
    return _builder.toString();
  }
}
