package org.eclipse.vorto.codegen.webui.templates.service.bosch.internal.model;

import org.eclipse.vorto.codegen.api.IFileTemplate;
import org.eclipse.vorto.codegen.api.InvocationContext;
import org.eclipse.vorto.codegen.webui.templates.TemplateUtils;
import org.eclipse.vorto.core.api.model.informationmodel.InformationModel;
import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class ThingImplTemplate implements IFileTemplate<InformationModel> {
  @Override
  public String getFileName(final InformationModel context) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("ThingImpl.java");
    return _builder.toString();
  }
  
  @Override
  public String getPath(final InformationModel context) {
    StringConcatenation _builder = new StringConcatenation();
    String _baseApplicationPath = TemplateUtils.getBaseApplicationPath(context);
    _builder.append(_baseApplicationPath, "");
    _builder.append("/service/bosch/internal/model");
    return _builder.toString();
  }
  
  @Override
  public String getContent(final InformationModel element, final InvocationContext context) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package com.example.iot.");
    String _name = element.getName();
    String _lowerCase = _name.toLowerCase();
    _builder.append(_lowerCase, "");
    _builder.append(".service.bosch.internal.model;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import java.text.ParseException;");
    _builder.newLine();
    _builder.append("import java.util.Date;");
    _builder.newLine();
    _builder.append("import java.util.HashMap;");
    _builder.newLine();
    _builder.append("import java.util.Map;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import org.apache.commons.lang3.builder.ToStringBuilder;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import com.example.iot.");
    String _name_1 = element.getName();
    String _lowerCase_1 = _name_1.toLowerCase();
    _builder.append(_lowerCase_1, "");
    _builder.append(".service.bosch.model.Feature;");
    _builder.newLineIfNotEmpty();
    _builder.append("import com.example.iot.");
    String _name_2 = element.getName();
    String _lowerCase_2 = _name_2.toLowerCase();
    _builder.append(_lowerCase_2, "");
    _builder.append(".service.bosch.model.Thing;");
    _builder.newLineIfNotEmpty();
    _builder.append("import com.fasterxml.jackson.annotation.JsonIgnore;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class ThingImpl implements Thing {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private String thingId;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private Map<String, Object> attributes = new HashMap<String, Object>();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private Map<String, Object> features = new HashMap<String, Object>();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static final String ATTRIBUTE_MODELID = \"_modelId\";");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static final String ATTRIBUTE_CREATEDON = \"createdOn\";");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static final String ATTRIBUTE_CREATEDBY = \"createdBy\";");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static final String ATTRIBUTE_NAME = \"thingName\";");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static final String ATTRIBUTE_DEVICEID = \"deviceId\";");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ThingImpl() {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getThingId() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return thingId;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setThingId(String thingId) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.thingId = thingId;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public Map<String, Object> getAttributes() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return attributes;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setAttributes(Map<String, Object> attributes) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.attributes = attributes;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public Map<String, Object> getFeatures() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return features;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setFeatures(Map<String, Object> features) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.features = features;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String toString() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return ToStringBuilder.reflectionToString(this);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@JsonIgnore");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getThingTypeId() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return (String) this.attributes.get(ATTRIBUTE_MODELID);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@JsonIgnore");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public boolean hasThingType() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return this.attributes.containsKey(ATTRIBUTE_MODELID);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public Map<String, Object> listAttributes() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return this.attributes;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@SuppressWarnings(\"unchecked\")");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public Map<String, Feature> listFeatures() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Map<String, Feature> features = new HashMap<String, Feature>(this.features.size());");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for (String featureKey : this.features.keySet()) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("FeatureImpl feature = new FeatureImpl(featureKey, (Map<String, Object>) this.features.get(featureKey));");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("features.put(featureKey, feature);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return features;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@JsonIgnore");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getId() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return this.thingId;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@JsonIgnore");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getName() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return (String) this.attributes.get(ATTRIBUTE_NAME);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@JsonIgnore");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public Date getCreatedOn() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("String createdOn = (String) this.attributes.get(ATTRIBUTE_CREATEDON);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("if (createdOn != null) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("return JSON_DATE_FORMAT.parse(createdOn);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("} catch (ParseException e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("throw new RuntimeException(\"Cannot parse createdOn attribute. Seems to have unexpected format\");");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("return null;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@JsonIgnore");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getDeviceId() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return (String) this.attributes.get(ATTRIBUTE_DEVICEID);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@JsonIgnore");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getCreator() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return (String) this.attributes.get(ATTRIBUTE_CREATEDBY);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    return _builder.toString();
  }
}
