/**
 * Copyright (c) 2015 Bosch Software Innovations GmbH and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v1.0 which accompany this distribution.
 * 
 * The Eclipse Public License is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * The Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 * 
 * Contributors:
 * Bosch Software Innovations GmbH - Please refer to git log
 */
package org.eclipse.vorto.codegen.ios.templates;

import org.eclipse.emf.common.util.EList;
import org.eclipse.vorto.codegen.api.IFileTemplate;
import org.eclipse.vorto.codegen.api.InvocationContext;
import org.eclipse.vorto.core.api.model.datatype.EnumLiteral;
import org.eclipse.xtend2.lib.StringConcatenation;

/**
 * @author Alexander Edelmann - Robert Bosch (SEA) Pte. Ltd.
 */
@SuppressWarnings("all")
public class EnumClassTemplate implements IFileTemplate<org.eclipse.vorto.core.api.model.datatype.Enum> {
  @Override
  public String getFileName(final org.eclipse.vorto.core.api.model.datatype.Enum context) {
    String _name = context.getName();
    return (_name + ".swift");
  }
  
  @Override
  public String getPath(final org.eclipse.vorto.core.api.model.datatype.Enum context) {
    return "";
  }
  
  @Override
  public String getContent(final org.eclipse.vorto.core.api.model.datatype.Enum context, final InvocationContext invocationContext) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("//Generated by Vorto");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import Foundation");
    _builder.newLine();
    _builder.newLine();
    _builder.append("enum ");
    String _name = context.getName();
    _builder.append(_name, "");
    _builder.append(" {");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    {
      EList<EnumLiteral> _enums = context.getEnums();
      for(final EnumLiteral literal : _enums) {
        _builder.append("\t");
        _builder.append("case ");
        String _name_1 = literal.getName();
        _builder.append(_name_1, "\t");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }
}
